---
# TEHTRIS EDR Installation Task using Python Automation

- name: Create temp directory on Windows machine
  win_file:
    path: "C:\\Temp"
    state: directory

- name: Install Python if not present
  win_chocolatey:
    name: python
    state: present
  ignore_errors: true

- name: Copy TEHTRIS EDR MSI to Windows machine
  win_copy:
    src: "../res/TEHTRIS_EDR_2.0.0_Windows_x86_64_MS-28.msi"
    dest: "C:\\Temp\\TEHTRIS_EDR_2.0.0_Windows_x86_64_MS-28.msi"
    force: yes

- name: Copy Python automation script to Windows machine
  win_copy:
    src: "../res/tehtris_edr_installer_minimal.py"
    dest: "C:\\Temp\\tehtris_edr_installer_minimal.py"
    force: yes

- name: Copy requirements.txt to Windows machine
  win_copy:
    src: "../res/requirements.txt"
    dest: "C:\\Temp\\requirements.txt"
    force: yes

- name: Install Python dependencies
  win_shell: |
    cd C:\Temp
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  register: pip_install
  ignore_errors: true

- name: Display pip install results
  debug:
    msg: "Pip install output: {{ pip_install.stdout }}"
  when: pip_install.stdout is defined