#!/bin/bash
# SSH connection script for ${instance_name}
# Generated by Terraform

echo "Connecting to ${instance_name} (${ip_address})..."

%{ if ssh_key_file != "" ~}
ssh -i "${ssh_key_file}" -o StrictHostKeyChecking=no ${username}@${ip_address}
%{ else ~}
ssh -o StrictHostKeyChecking=no ${username}@${ip_address}
%{ endif ~}
