# Ansible Inventory Generated by Terraform

# Windows instances
%{ if length([for i in instances : i if i.os_type == "windows"]) > 0 ~}
[windows_client:vars]
ansible_connection=winrm
ansible_user=${ansible_user != "" ? ansible_user : "Admin"}
ansible_password="${windows_password}"
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
ansible_winrm_scheme=http
ansible_port=5985

# Windows-specific variables
hardcore_mode=False
set_powerplan=False
change_hostname=False
set_spy_block_hosts=False
disable_defender=False
cleanup=False

[windows_client]
%{ for instance in instances ~}
%{ if instance.os_type == "windows" ~}
${instance.name} ansible_host=${instance.has_floating_ip && instance.public_ip != null ? instance.public_ip : (instance.private_ip != null ? instance.private_ip : "pending")}
%{ endif ~}
%{ endfor ~}

%{ endif ~}

# Linux instances
%{ if length([for i in instances : i if i.os_type == "linux"]) > 0 ~}
[linux_servers:vars]
ansible_connection=ssh
ansible_user=${ansible_user != "" ? ansible_user : "ubuntu"}
%{ if ansible_ssh_private_key_file != "" ~}
ansible_ssh_private_key_file=${ansible_ssh_private_key_file}
%{ endif ~}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[linux_servers]
%{ for instance in instances ~}
%{ if instance.os_type == "linux" ~}
${instance.name} ansible_host=${instance.has_floating_ip && instance.public_ip != null ? instance.public_ip : (instance.private_ip != null ? instance.private_ip : "pending")}
%{ endif ~}
%{ endfor ~}

%{ endif ~}

# All hosts group
[all:vars]
# Common variables for all hosts
project_name=terraform-ansible-deployment
environment=dev

# Individual host details
%{ for instance in instances ~}
# ${instance.name}
%{ if instance.private_ip != null ~}
# Private IP: ${instance.private_ip}
%{ endif ~}
%{ if instance.has_floating_ip && instance.public_ip != null ~}
# Public IP: ${instance.public_ip}
%{ endif ~}
%{ endfor ~}
